DROP SCHEMA IF EXISTS FARMACIA
GO

CREATE SCHEMA FARMACIA
GO 

DROP TABLE IF EXISTS CATEGORIA_MEDICAMENTO
DROP TABLE IF EXISTS PRECAUCION
DROP TABLE IF EXISTS PROVEEDOR
DROP TABLE IF EXISTS DISTRIBUIDOR
DROP TABLE IF EXISTS FARMACIA
DROP TABLE IF EXISTS EMPLEADO
DROP TABLE IF EXISTS PERSONA
DROP TABLE IF EXISTS CLIENTES
DROP TABLE IF EXISTS MEDICAMENTO
DROP TABLE IF EXISTS RECETA_X_MEDICAMENTOS
DROP TABLE IF EXISTS RECETA_MEDICA
GO


CREATE TABLE CATEGORIA_MEDICAMENTO (
	ID_TIPO_MED					INT NOT NULL CONSTRAINT PK_TIPO_MED PRIMARY KEY,
	CATEGORIA_MED				VARCHAR(50),
	DESCRIPCION_CATEGORIA_MED	VARCHAR(200)
)
GO

CREATE TABLE PRECAUCION (
	ID_PRECAUCION		INT NOT NULL CONSTRAINT PK_PRECAUCION PRIMARY KEY, 
	EFECTOS_SECUNDARIOS	VARCHAR(300),
	FECHA_INDICACIÓN	DATE,
	ID_MEDICAMENTO		INT
)
GO

CREATE TABLE PROVEEDOR (
	ID_PROVEEDOR		INT NOT NULL CONSTRAINT PK_PROVEEDOR PRIMARY KEY, 
	NOMBRE_MARCA		VARCHAR(30), 
	DURACION_ACUERDO	INT,
	FECHA_INICIO		DATE,
	MESES_DURACION		INT
)
GO

CREATE TABLE DISTRIBUIDOR (
	ID_DISTRIBUIDOR		INT NOT NULL CONSTRAINT PK_DISTRIBUIDOR PRIMARY KEY, 
	ID_PERSONA			INT NOT NULL, 
	FECHA_INICIO		DATE, 
	ID_PROVEEDOR		INT, 
	ID_MEDICAMENTOS		INT
)
GO

CREATE TABLE FARMACIA (
	ID_FARMACIA			INT NOT NULL CONSTRAINT PK_FARMACIA PRIMARY KEY, 
	NOMBRE_FARMACIA		VARCHAR(30),
	CAPACIDAD			INT,
	UBICACION			VARCHAR(25), 
	AÑOS_EXISTENCIA		INT
)
GO

CREATE TABLE EMPLEADO (
	ID_EMPLEADO			INT NOT NULL CONSTRAINT PK_EMPLEADO PRIMARY KEY, 
	ID_PERSONA			INT NOT NULL, 
	FECHA_INICIO		DATE, 
	ID_FARMACIA			INT
)
GO

CREATE TABLE PERSONA (
	ID_PERSONA			INT NOT NULL CONSTRAINT PK_PERSONA PRIMARY KEY, 
	NOMBRE_PERSONA		VARCHAR(40),
	NOMBRE2_PERSONA		VARCHAR(40),
	APELLIDO1_PERSONA	VARCHAR(40),
	APELLIDO2_PERSONA	VARCHAR(40),
	CEDULA				INT,
	FECHA_NACIMIENTO	DATE
)
GO

CREATE TABLE CLIENTES (
	ID_CLIENTES			INT NOT NULL CONSTRAINT PK_CLIENTES PRIMARY KEY, 
	ID_PERSONA			INT, 
	FECHA_INICIO		DATE
)
GO

CREATE TABLE MEDICAMENTO (
	ID_MEDICAMENTO		INT NOT NULL CONSTRAINT PK_MEDICAMENTO PRIMARY KEY, 
	NOMBRE_MEDICAMENTO	VARCHAR(95), 
	DESCRIP_MEDICAMENTO	VARCHAR(100),
	CANTIDAD_ALMACEN	INT,
	FECHA_CADUCIDAD		DATE,
	ID_TIPO_MED			INT, 
	ID_FARMACIA			INT, 
	ID_EMPLEADO			INT
)
GO

CREATE TABLE RECETA_X_MEDICAMENTOS (
	CODIGO_RXM				INT NOT NULL CONSTRAINT PK_RXM PRIMARY KEY, 
	ID_MEDICAMENTO			INT,
	CODIGO_RECETA_MEDICA	INT
)
GO

CREATE TABLE RECETA_MEDICA (
	CODIGO_RECETA_MEDICA	INT NOT NULL CONSTRAINT PK_RECETA_MEDICA PRIMARY KEY, 
	DESCRIP_USO_MEDICO		VARCHAR(200), 
	CANTIDAD				INT, 
	ID_CLIENTE				INT, 
	FECHA					DATE
)
GO