USE MASTER
GO 

DROP DATABASE IF EXISTS FARMACIA_SA
GO

CREATE DATABASE FARMACIA_SA
GO

USE FARMACIA_SA
GO

DROP TABLE IF EXISTS PROVEEDOR_SA
DROP TABLE IF EXISTS FARMACIA_SA
DROP TABLE IF EXISTS EMPLEADO_SA
DROP TABLE IF EXISTS CLIENTES_SA
DROP TABLE IF EXISTS MEDICAMENTO_SA
DROP TABLE IF EXISTS DISTRIBUIDOR_SA
DROP TABLE IF EXISTS RECETA_MEDICA_SA
DROP TABLE IF EXISTS RECETA_X_MEDICAMENTOS_SA
DROP TABLE IF EXISTS PRECAUCION_SA
DROP TABLE IF EXISTS CATEGORIA_MEDICAMENTO_SA
DROP TABLE IF EXISTS PERSONA_SA
GO

CREATE TABLE CATEGORIA_MEDICAMENTO_SA (
	ID_TIPO_MED					VARCHAR(255),
	CATEGORIA_MED				VARCHAR(255),
	DESCRIPCION_CATEGORIA_MED	VARCHAR(255)
)
GO

CREATE TABLE PROVEEDOR_SA (
	ID_PROVEEDOR		VARCHAR(255),
	NOMBRE_MARCA		VARCHAR(255),
	DURACION_ACUERDO	VARCHAR(255),
	FECHA_INICIO		VARCHAR(255),
	MESES_DURACION		VARCHAR(255),
)
GO

CREATE TABLE PERSONA_SA (
	ID_PERSONA			VARCHAR(255),
	NOMBRE_PERSONA		VARCHAR(255),
	NOMBRE2_PERSONA		VARCHAR(255),
	APELLIDO1_PERSONA	VARCHAR(255),
	APELLIDO2_PERSONA	VARCHAR(255),
	CEDULA				VARCHAR(255),
	FECHA_NACIMIENTO	VARCHAR(255)
)
GO

CREATE TABLE FARMACIA_SA (
	ID_FARMACIA			VARCHAR(255),
	NOMBRE_FARMACIA		VARCHAR(255),
	CAPACIDAD			VARCHAR(255),
	UBICACION			VARCHAR(255), 
	AÑOS_EXISTENCIA		VARCHAR(255)
)
GO

CREATE TABLE EMPLEADO_SA (
	ID_EMPLEADO			VARCHAR(255),
	ID_PERSONA			VARCHAR(255),
	FECHA_INICIO		VARCHAR(255),
	ID_FARMACIA			VARCHAR(255)
)
GO

CREATE TABLE CLIENTES_SA (
	ID_CLIENTES			VARCHAR(255),
	ID_PERSONA			VARCHAR(255), 
	FECHA_INICIO		VARCHAR(255)
)
GO

CREATE TABLE MEDICAMENTO_SA (
	ID_MEDICAMENTO		VARCHAR(255),
	NOMBRE_MEDICAMENTO	VARCHAR(255), 
	DESCRIP_MEDICAMENTO	VARCHAR(255),
	CANTIDAD_ALMACEN	VARCHAR(255),
	FECHA_CADUCIDAD		VARCHAR(255),
	ID_TIPO_MED			VARCHAR(255), 
	ID_FARMACIA			VARCHAR(255), 
)
GO

CREATE TABLE DISTRIBUIDOR_SA (
	ID_DISTRIBUIDOR		VARCHAR(255),
	ID_PERSONA			VARCHAR(255), 
	FECHA_INICIO		VARCHAR(255),
	ID_PROVEEDOR		VARCHAR(255), 
	ID_MEDICAMENTOS		VARCHAR(255)
)
GO

CREATE TABLE RECETA_MEDICA_SA (
	CODIGO_RECETA_MEDICA	VARCHAR(255),
	DESCRIP_USO_MEDICO		VARCHAR(255),
	CANTIDAD				VARCHAR(255),
	ID_CLIENTE				VARCHAR(255), 
	FECHA					VARCHAR(255)
)
GO

CREATE TABLE RECETA_X_MEDICAMENTOS_SA (
	CODIGO_RXM				VARCHAR(255),
	ID_MEDICAMENTO			VARCHAR(255),
	CODIGO_RECETA_MEDICA	VARCHAR(255)
)
GO

CREATE TABLE PRECAUCION_SA (
	ID_PRECAUCION		VARCHAR(255),
	EFECTOS_SECUNDARIOS	VARCHAR(255),
	FECHA_INDICACIÓN	VARCHAR(255),
	ID_MEDICAMENTO		VARCHAR(255)
)
GO