USE MASTER
GO

DROP DATABASE IF EXISTS FARMACIA_DW
GO

CREATE DATABASE FARMACIA_DW
GO

USE FARMACIA_DW
GO

IF EXISTS (
	SELECT 'X'
	FROM SYS.SYSOBJECTS
	WHERE TYPE = 'P' AND NAME = 'SA_EXTRACCION'
)
	DROP PROCEDURE SA_EXTRACCION
GO

CREATE PROCEDURE SA_EXTRACCION AS
BEGIN 
	
	---------------------------------------------------------------------
	-- TABLA: CATEGORIA_MEDICAMENTO_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'CATEGORIA_MEDICAMENTO_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.CATEGORIA_MEDICAMENTO_SA
		INSERT INTO FARMACIA_SA.DBO.CATEGORIA_MEDICAMENTO_SA (ID_TIPO_MED, CATEGORIA_MED, DESCRIPCION_CATEGORIA_MED)
			SELECT
				ID_TIPO_MED,
				CATEGORIA_MED,
				DESCRIPCION_CATEGORIA_MED
			FROM FARMACIA_ER.DBO.CATEGORIA_MEDICAMENTO
	
	---------------------------------------------------------------------
	-- TABLA: PROVEEDOR_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'PROVEEDOR_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.PROVEEDOR_SA
		INSERT INTO FARMACIA_SA.DBO.PROVEEDOR_SA(ID_PROVEEDOR, NOMBRE_MARCA, DURACION_ACUERDO, FECHA_INICIO, MESES_DURACION)
			SELECT
				ID_PROVEEDOR, 
				NOMBRE_MARCA, 
				DURACION_ACUERDO, 
				FECHA_INICIO, 
				MESES_DURACION
			FROM FARMACIA_ER.DBO.PROVEEDOR

	---------------------------------------------------------------------
	-- TABLA: PERSONA_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'PERSONA_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.PERSONA_SA
		INSERT INTO FARMACIA_SA.DBO.PERSONA_SA(ID_PERSONA,NOMBRE_PERSONA,NOMBRE2_PERSONA,APELLIDO1_PERSONA,APELLIDO2_PERSONA,CEDULA,FECHA_NACIMIENTO)
			SELECT
				ID_PERSONA,
				NOMBRE_PERSONA,
				NOMBRE2_PERSONA,
				APELLIDO1_PERSONA,
				APELLIDO2_PERSONA,
				CEDULA,
				FECHA_NACIMIENTO
			FROM FARMACIA_ER.DBO.PERSONA

	---------------------------------------------------------------------
	-- TABLA: FARMACIA_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'FARMACIA_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.FARMACIA_SA
		INSERT INTO FARMACIA_SA.DBO.FARMACIA_SA(ID_FARMACIA,NOMBRE_FARMACIA,CAPACIDAD,UBICACION,AÑOS_EXISTENCIA)
			SELECT
				ID_FARMACIA,
				NOMBRE_FARMACIA,
				CAPACIDAD,
				UBICACION,
				AÑOS_EXISTENCIA
			FROM FARMACIA_ER.DBO.FARMACIA

	---------------------------------------------------------------------
	-- TABLA: EMPLEADO_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'EMPLEADO_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.EMPLEADO_SA
		INSERT INTO FARMACIA_SA.DBO.EMPLEADO_SA(ID_EMPLEADO, ID_PERSONA, FECHA_INICIO, ID_FARMACIA)
			SELECT
				ID_EMPLEADO, 
				ID_PERSONA, 
				FECHA_INICIO, 
				ID_FARMACIA
			FROM FARMACIA_ER.DBO.EMPLEADO

	---------------------------------------------------------------------
	-- TABLA: CLIENTES_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'CLIENTES_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.CLIENTES_SA
		INSERT INTO FARMACIA_SA.DBO.CLIENTES_SA(ID_CLIENTES, ID_PERSONA, FECHA_INICIO)
			SELECT
				ID_CLIENTES, 
				ID_PERSONA, 
				FECHA_INICIO
			FROM FARMACIA_ER.DBO.CLIENTES

	---------------------------------------------------------------------
	-- TABLA: MEDICAMENTO_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'MEDICAMENTO_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.MEDICAMENTO_SA
		INSERT INTO FARMACIA_SA.DBO.MEDICAMENTO_SA(ID_MEDICAMENTO, NOMBRE_MEDICAMENTO, DESCRIP_MEDICAMENTO, CANTIDAD_ALMACEN, FECHA_CADUCIDAD, ID_TIPO_MED,ID_FARMACIA)
			SELECT
				ID_MEDICAMENTO,
				NOMBRE_MEDICAMENTO,
				DESCRIP_MEDICAMENTO,
				CANTIDAD_ALMACEN,
				FECHA_CADUCIDAD,
				ID_TIPO_MED,
				ID_FARMACIA
			FROM FARMACIA_ER.DBO.MEDICAMENTO

	---------------------------------------------------------------------
	-- TABLA: DISTRIBUIDOR_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'DISTRIBUIDOR_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.DISTRIBUIDOR_SA
		INSERT INTO FARMACIA_SA.DBO.DISTRIBUIDOR_SA(ID_DISTRIBUIDOR, ID_PERSONA, FECHA_INICIO, ID_PROVEEDOR, ID_MEDICAMENTOS)
			SELECT
				ID_DISTRIBUIDOR, 
				ID_PERSONA, 
				FECHA_INICIO, 
				ID_PROVEEDOR, 
				ID_MEDICAMENTOS
			FROM FARMACIA_ER.DBO.DISTRIBUIDOR

	---------------------------------------------------------------------
	-- TABLA: RECETA_MEDICA_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'RECETA_MEDICA_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.RECETA_MEDICA_SA
		INSERT INTO FARMACIA_SA.DBO.RECETA_MEDICA_SA(CODIGO_RECETA_MEDICA, DESCRIP_USO_MEDICO, CANTIDAD, ID_CLIENTE,FECHA)
			SELECT
				CODIGO_RECETA_MEDICA, 
				DESCRIP_USO_MEDICO, 
				CANTIDAD, 
				ID_CLIENTE,
				FECHA
			FROM FARMACIA_ER.DBO.RECETA_MEDICA

	---------------------------------------------------------------------
	-- TABLA: RECETA_X_MEDICAMENTOS_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'RECETA_X_MEDICAMENTOS_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.RECETA_X_MEDICAMENTOS_SA
		INSERT INTO FARMACIA_SA.DBO.RECETA_X_MEDICAMENTOS_SA(CODIGO_RXM,ID_MEDICAMENTO,CODIGO_RECETA_MEDICA)
			SELECT
				CODIGO_RXM,
				ID_MEDICAMENTO,
				CODIGO_RECETA_MEDICA
			FROM FARMACIA_ER.DBO.RECETA_X_MEDICAMENTOS

	---------------------------------------------------------------------
	-- TABLA: PRECAUCION_SA
	---------------------------------------------------------------------
	IF EXISTS(
		SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE_TABLE' AND TABLE_NAME = 'PRECAUCION_SA'
	)
		DELETE FROM FARMACIA_SA.DBO.PRECAUCION_SA
		INSERT INTO FARMACIA_SA.DBO.PRECAUCION_SA(ID_PRECAUCION, EFECTOS_SECUNDARIOS, FECHA_INDICACIÓN, ID_MEDICAMENTO)
			SELECT
				ID_PRECAUCION, 
				EFECTOS_SECUNDARIOS, 
				FECHA_INDICACIÓN, 
				ID_MEDICAMENTO
			FROM FARMACIA_ER.DBO.PRECAUCION

END
GO



