USE FARMACIA_DW
GO

DROP TABLE IF EXISTS DIM_CATEGORIA_MEDICAMENTO
DROP TABLE IF EXISTS DIM_PROVEEDOR
DROP TABLE IF EXISTS DIM_PERSONA
DROP TABLE IF EXISTS DIM_FARMACIA
DROP TABLE IF EXISTS DIM_EMPLEADO
DROP TABLE IF EXISTS DIM_CLIENTES
DROP TABLE IF EXISTS DIM_MEDICAMENTO
DROP TABLE IF EXISTS DIM_RECETA_MEDICA
DROP TABLE IF EXISTS DIM_PRECAUCIÓN
DROP TABLE IF EXISTS DIM_FECHA
DROP TABLE IF EXISTS FAC_FARMACIA
GO

CREATE TABLE DIM_CATEGORIA_MEDICAMENTO (
	ID_TIPO_MED					INTEGER NOT NULL CONSTRAINT PK_DCM_ID PRIMARY KEY,
	CATEGORIA_MED				VARCHAR(100),
	DESCRIPCION_CATEGORIA_MED	VARCHAR(100)
)
GO

CREATE TABLE DIM_PROVEEDOR (
	ID_PROVEEDOR INTEGER NOT NULL CONSTRAINT PK_DPROVEEDOR_ID PRIMARY KEY,
	NOMBRE_MARCA VARCHAR(100)
)
GO

CREATE TABLE DIM_PERSONA (
	ID_PERSONA			INTEGER NOT NULL CONSTRAINT PK_DPERSONA PRIMARY KEY,
	NOMBRE_PERSONA		VARCHAR(50),
	NOMBRE2_PERSONA		VARCHAR(50),
	APELLIDO1_PERSONA	VARCHAR(50),
	APELLIDO2_PERSONA	VARCHAR(50),
	CEDULA				VARCHAR(50)
)
GO

CREATE TABLE DIM_FARMACIA (
	ID_FARMACIA		INTEGER NOT NULL CONSTRAINT PK_DF PRIMARY KEY,
	NOMBRE_FARMACIA	VARCHAR(50),
	UBICACIÓN		VARCHAR(50)
)
GO

CREATE TABLE DIM_MEDICAMENTO (
	ID_MEDICAMENTO		INTEGER NOT NULL CONSTRAINT PK_DM PRIMARY KEY,
	NOMBRE_MEDICAMENTO	VARCHAR(50),
	DESCRIP_MEDICAMENTO	VARCHAR(50)
)
GO

CREATE TABLE DIM_RECETA_MEDICA (
	CODIGO_RECETA_MEDICA	INTEGER NOT NULL CONSTRAINT PK_DRM PRIMARY KEY,
	DESCRIP_USO_MEDICO		VARCHAR(50)
)
GO

CREATE TABLE DIM_PRECAUCIÓN (
	ID_PRECAUCIÓN INTEGER NOT NULL CONSTRAINT PK_DPRECAUCIÓN PRIMARY KEY, 
	EFECTOS_SECUNDARIOS VARCHAR(255)
)
GO

CREATE TABLE DIM_FECHA(
   FEC_ID                INTEGER NOT NULL CONSTRAINT PK_FECH_ID PRIMARY KEY, /* Format: AAAAMMDD */
   FEC_FECHA             datetime NOT NULL,        /* Actual date */
   FEC_DIA_SEMANA        tinyint NULL,             /* 1 to 7 */
   FEC_DIA_MES           tinyint NULL,             /* 1 to 31 */
   FEC_DIA_PERIODO       smallint NULL,            /* 1 to 366 */
   FEC_SEMANA            tinyint NULL,             /* 1 to 53 */
   FEC_MES               tinyint NULL,             /* 1 to 12 */
   FEC_TRIMESTRE         tinyint NULL,             /* 1 to 4 */
   FEC_SEMESTRE          tinyint NULL,             /* 1 to 2 */
   FEC_PERIODO           char(4) NULL,             /* Just the number */
   FEC_SEMANA_PERIODO    nvarchar(25) NULL,        /* Week Unique Identifier: Week + Year */
   FEC_MES_PERIODO       nvarchar(25) NULL,        /* Month Unique Identifier: Month + Year */
   FEC_TRIMESTRE_PERIODO nvarchar(25) NULL,        /* Quarter Unique Identifier: Quarter + Year */
   FEC_SEMESTRE_PERIODO  nvarchar(25) NULL,        /* Semester Unique Identifier: Semester + Year */
   FEC_DIA_SEMANA_ENG    nvarchar(10) NULL,
   FEC_DIA_SEMANA_ESP    nvarchar(10) NULL,
   FEC_NOMBRE_MES_ING    nvarchar(10) NULL,        /* January to December */
   FEC_NOMBRE_MES_ESP    nvarchar(10) NULL,        /* Enero a Diciembre */
)
GO


CREATE TABLE FAC_FARMACIA (
	ID_TIPO_MED	INTEGER NOT NULL,
	ID_PROVEEDOR INTEGER NOT NULL, 
	ID_PERSONA	INTEGER NOT NULL, 
	ID_FARMACIA	INTEGER NOT NULL,
	ID_EMPLEADO INTEGER NOT NULL,
	ID_CLIENTE INTEGER NOT NULL,
	ID_MEDICAMENTO INTEGER NOT NULL,
	ID_DISTRIBUIDOR	INTEGER NOT NULL,
	CODIGO_RECETA_MEDICA	INTEGER NOT NULL,
	ID_PRECAUCIÓN INTEGER NOT NULL,
	DURACION_ACUERDO	INTEGER NOT NULL,
	FECHA_INICIO_PROVEEDOR	INTEGER NOT NULL,
	MESES_DURACION	INTEGER NOT NULL,
	FECHA_NACIMIENTO_PERSONA	INTEGER NOT NULL,
	CAPACIDAD	INTEGER NOT NULL,
	AÑOS_EXPERIENCIA	INTEGER NOT NULL,
	FECHA_INICIO_EMPLEADO	INTEGER NOT NULL,
	FECHA_INICIO_CLIENTES	INTEGER NOT NULL,
	CANTIDAD_ALMACEN	INTEGER NOT NULL,
	FECHA_CADUCIDAD_MEDICAMENTO	INTEGER NOT NULL,
	FECHA_INICIO_DISTRIBUIDOR	INTEGER NOT NULL,
	CANTIDAD	INTEGER NOT NULL,
	FECHA_RECETA_MEDICA	INTEGER NOT NULL,
	FECHA_INDICACIÓN INTEGER NOT NULL
	CONSTRAINT FK_FF_DCM FOREIGN KEY (ID_TIPO_MED) REFERENCES DIM_CATEGORIA_MEDICAMENTO(ID_TIPO_MED), 
	CONSTRAINT FK_FF_DPROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES DIM_PROVEEDOR (ID_PROVEEDOR), 
	CONSTRAINT FK_FF_DPERSONA FOREIGN KEY (ID_PERSONA) REFERENCES DIM_PERSONA (ID_PERSONA), 
	CONSTRAINT FK_FF_DF FOREIGN KEY (ID_FARMACIA) REFERENCES DIM_FARMACIA (ID_FARMACIA), 
	CONSTRAINT FK_FF_DM FOREIGN KEY (ID_MEDICAMENTO) REFERENCES DIM_MEDICAMENTO (ID_MEDICAMENTO), 
	CONSTRAINT FK_FF_DRM FOREIGN KEY (CODIGO_RECETA_MEDICA) REFERENCES DIM_RECETA_MEDICA (CODIGO_RECETA_MEDICA),
	CONSTRAINT FK_FF_DPRECAUCION FOREIGN KEY (ID_PRECAUCIÓN) REFERENCES DIM_PRECAUCIÓN (ID_PRECAUCIÓN),
	CONSTRAINT FK_FF_FECHA_PROVEEDOR FOREIGN KEY (FECHA_INICIO_PROVEEDOR) REFERENCES DIM_FECHA (FEC_ID),
	CONSTRAINT FK_FF_FECHA_PERSONA FOREIGN KEY (FECHA_NACIMIENTO_PERSONA) REFERENCES DIM_FECHA (FEC_ID),
	CONSTRAINT FK_FF_FECHA_EMPLEADO FOREIGN KEY (FECHA_INICIO_EMPLEADO) REFERENCES DIM_FECHA (FEC_ID),
	CONSTRAINT FK_FF_FECHA_CLIENTES FOREIGN KEY (FECHA_INICIO_CLIENTES) REFERENCES DIM_FECHA (FEC_ID),
	CONSTRAINT FK_FF_FECHA_MEDICAMENTO FOREIGN KEY (FECHA_CADUCIDAD_MEDICAMENTO) REFERENCES DIM_FECHA (FEC_ID),
	CONSTRAINT FK_FF_FECHA_DISTRTIBUIDOR FOREIGN KEY (FECHA_INICIO_DISTRIBUIDOR)REFERENCES DIM_FECHA (FEC_ID),
	CONSTRAINT FK_FF_FECHA_MEDICA FOREIGN KEY (FECHA_RECETA_MEDICA) REFERENCES DIM_FECHA (FEC_ID),
	CONSTRAINT FK_FF_FECHA_INDICACIÓN FOREIGN KEY (FECHA_INDICACIÓN) REFERENCES DIM_FECHA (FEC_ID)
)
GO