USE FARMACIA_DW
GO

IF EXISTS(SELECT 'X'
            FROM sys.objects
			WHERE type = 'P' AND name = 'EXRACCION_DATOS_DW')
   DROP PROCEDURE EXRACCION_DATOS_DW
GO

CREATE PROCEDURE EXRACCION_DATOS_DW(@FechaInicio varchar(10), @FechaFinal varchar(10)) AS
BEGIN
-----------------------------------------------------------------------------------------
-- Tabla: PERSONA
-----------------------------------------------------------------------------------------
   DECLARE
      @vERROR_DATOS       INTEGER,
      @VMENSAJE_ERROR     VARCHAR(4000)

   IF EXISTS (SELECT 'X'
                FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_TYPE='BASE TABLE' 
                 AND TABLE_NAME='DIM_PERSONA')
      IF EXISTS (SELECT 'X'
                   FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES 
                  WHERE TABLE_TYPE='BASE TABLE' 
                    AND TABLE_NAME='PERSONA_SA')
	     BEGIN
		    DECLARE
               @vID_PERSONA            INTEGER,
		       @vNOMBRE_PERSONA		  VARCHAR(50),
			   @vNOMBRE2_PERSONA		  VARCHAR(50),
			   @vAPELLIDO1_PERSONA	  VARCHAR(50),
			   @vAPELLIDO2_PERSONA	  VARCHAR(50),
			   @vCEDULA				  VARCHAR(50)			
			DECLARE C_PERSONA CURSOR FOR
			   SELECT ID_PERSONA,
			          NOMBRE_PERSONA,
					  NOMBRE2_PERSONA,
					  APELLIDO1_PERSONA,
					  APELLIDO2_PERSONA,
					  CEDULA			
			     FROM FARMACIA_SA.dbo.PERSONA_SA SCTA
				WHERE NOT EXISTS (SELECT 'X'
				                    FROM DIM_PERSONA DCTA
								   WHERE DCTA.ID_PERSONA != SCTA.ID_PERSONA)
		    BEGIN
			  SET @VMENSAJE_ERROR = ''
			  SET @vERROR_DATOS   = 0
               OPEN C_PERSONA
			   FETCH NEXT FROM C_PERSONA INTO @vID_PERSONA, @vNOMBRE_PERSONA,@vNOMBRE2_PERSONA,@vAPELLIDO1_PERSONA,@vAPELLIDO2_PERSONA,@vCEDULA
			   WHILE @@FETCH_STATUS = 0
			   BEGIN
			      SET @vERROR_DATOS = 0
			      IF ISNUMERIC(@vID_PERSONA) = 0 OR @vID_PERSONA IS NULL
					 SET @vERROR_DATOS = 1

				  IF @vNOMBRE_PERSONA IS NULL OR LEN(@vNOMBRE_PERSONA) > 50 
				     SET @vERROR_DATOS = 1

				  IF LEN(@vNOMBRE2_PERSONA) > 50 
				     SET @vERROR_DATOS = 1

				  IF @vAPELLIDO1_PERSONA IS NULL OR LEN(@vAPELLIDO1_PERSONA) > 50 
				     SET @vERROR_DATOS = 1

				  IF LEN(@vAPELLIDO2_PERSONA) > 50 
				     SET @vERROR_DATOS = 1

				  IF @vCEDULA IS NULL OR LEN(@vCEDULA) > 50 OR LEN(@vCEDULA) <=13
				     SET @vERROR_DATOS = 1

				  IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN CUENTA: ' + @vID_PERSONA + ' NUM.PER.' + @vNOMBRE_PERSONA + @vNOMBRE2_PERSONA + @vAPELLIDO1_PERSONA + @vAPELLIDO2_PERSONA + @vCEDULA
				  ELSE
			         INSERT INTO DIM_PERSONA(ID_PERSONA, NOMBRE_PERSONA, NOMBRE2_PERSONA,APELLIDO1_PERSONA,APELLIDO2_PERSONA,CEDULA)
					                VALUES (CONVERT(INTEGER,@vID_PERSONA), @vNOMBRE_PERSONA,@vNOMBRE2_PERSONA,@vAPELLIDO1_PERSONA,@vAPELLIDO2_PERSONA,@vCEDULA)
			      FETCH NEXT FROM C_PERSONA INTO @vID_PERSONA, @vNOMBRE_PERSONA,@vNOMBRE2_PERSONA,@vAPELLIDO1_PERSONA,@vAPELLIDO2_PERSONA,@vCEDULA
			   END
			   CLOSE C_PERSONA
			   DEALLOCATE C_PERSONA
	        END
		END
-----------------------------------------------------------------------------------------
-- Tabla: MEDICAMENTO.
-----------------------------------------------------------------------------------------
   IF EXISTS (SELECT 'X'
                FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_TYPE='BASE TABLE' 
                 AND TABLE_NAME='DIM_MEDICAMENTO')
      IF EXISTS (SELECT 'X'
                   FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES 
                  WHERE TABLE_TYPE='BASE TABLE' 
                    AND TABLE_NAME='MEDICAMENTO_SA')
	     BEGIN
		    DECLARE
               @vID_MEDICAMENTO            INTEGER,
		       @vNOMBRE_MEDICAMENTO        VARCHAR(50),
			   @vDESCRIP_MEDICAMENTO       VARCHAR(50)
			DECLARE C_MED CURSOR FOR
			   SELECT ID_MEDICAMENTO,
			          NOMBRE_MEDICAMENTO,
					  DESCRIP_MEDICAMENTO
			     FROM FARMACIA_SA.dbo.MEDICAMENTO_SA SADATA
				WHERE NOT EXISTS (SELECT 'X'
				                    FROM DIM_MEDICAMENTO DWDATA
								   WHERE DWDATA.ID_MEDICAMENTO != SADATA.ID_MEDICAMENTO)
		    BEGIN
			  SET @VMENSAJE_ERROR = ''
			  SET @vERROR_DATOS   = 0
               OPEN C_MED
			   FETCH NEXT FROM C_MED INTO @vID_MEDICAMENTO, @vNOMBRE_MEDICAMENTO
			   WHILE @@FETCH_STATUS = 0
			   BEGIN
			      SET @vERROR_DATOS = 0
			      IF ISNUMERIC(@vID_MEDICAMENTO) = 0 OR @vID_MEDICAMENTO IS NULL
					 SET @vERROR_DATOS = 1

				  IF @vNOMBRE_MEDICAMENTO IS NULL OR LEN(@vNOMBRE_MEDICAMENTO) > 50 or LEN(@vNOMBRE_MEDICAMENTO) <= 2
				     SET @vERROR_DATOS = 1

			      IF @vDESCRIP_MEDICAMENTO IS NULL OR LEN(@vDESCRIP_MEDICAMENTO) > 50 or LEN(@vDESCRIP_MEDICAMENTO) <= 5
				     SET @vERROR_DATOS = 1

				  IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN ESTADO DE CLIENTE: ' + @vID_MEDICAMENTO + ' NOMBRE:' + @vNOMBRE_MEDICAMENTO + ' DESCRIPCIÓN:' + @vDESCRIP_MEDICAMENTO
				  ELSE
			         INSERT INTO DIM_MEDICAMENTO(ID_MEDICAMENTO, NOMBRE_MEDICAMENTO,DESCRIP_MEDICAMENTO)
					                VALUES (CONVERT(INTEGER,@vID_MEDICAMENTO), @vNOMBRE_MEDICAMENTO,@vDESCRIP_MEDICAMENTO)
			      FETCH NEXT FROM C_MED INTO @vID_MEDICAMENTO, @vNOMBRE_MEDICAMENTO, @vDESCRIP_MEDICAMENTO
			   END
			   CLOSE C_MED
			   DEALLOCATE C_MED
	        END
		END
-----------------------------------------------------------------------------------------
-- Tabla: RECETA_MEDICA.
-----------------------------------------------------------------------------------------
IF EXISTS (SELECT 'X'
                FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_TYPE='BASE TABLE' 
                 AND TABLE_NAME='DIM_RECETA_MEDICA')
      IF EXISTS (SELECT 'X'
                   FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES 
                  WHERE TABLE_TYPE='BASE TABLE' 
                    AND TABLE_NAME='RECETA_MEDICA_SA')
	     BEGIN
		    DECLARE
               @vCODIGO_RECETA_MEDICA            INTEGER,
			   @vDESCRIP_USO_MEDICO				 VARCHAR(50)
			DECLARE C_RECM CURSOR FOR
			   SELECT CODIGO_RECETA_MEDICA,
			          DESCRIP_USO_MEDICO
			     FROM FARMACIA_SA.dbo.RECETA_MEDICA_SA SADATA
				WHERE NOT EXISTS (SELECT 'X'
				                    FROM DIM_RECETA_MEDICA DWDATARM
								   WHERE DWDATARM.CODIGO_RECETA_MEDICA != SADATA.CODIGO_RECETA_MEDICA)
		    BEGIN
			  SET @VMENSAJE_ERROR = ''
			  SET @vERROR_DATOS   = 0
               OPEN C_RECM
			   FETCH NEXT FROM C_RECM INTO @vCODIGO_RECETA_MEDICA, @vDESCRIP_USO_MEDICO
			   WHILE @@FETCH_STATUS = 0
			   BEGIN
			      SET @vERROR_DATOS = 0
			      IF ISNUMERIC(@vCODIGO_RECETA_MEDICA) = 0 OR @vCODIGO_RECETA_MEDICA IS NULL
					 SET @vERROR_DATOS = 1

				  IF @vDESCRIP_USO_MEDICO IS NULL OR LEN(@vDESCRIP_USO_MEDICO) > 50 or LEN(@vDESCRIP_USO_MEDICO) <= 2
				     SET @vERROR_DATOS = 1

				  IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN ESTADO DE CLIENTE: ' + @vCODIGO_RECETA_MEDICA + ' DESCRIPCIÓN:' + @vDESCRIP_USO_MEDICO
				  ELSE
			         INSERT INTO DIM_RECETA_MEDICA(CODIGO_RECETA_MEDICA, DESCRIP_USO_MEDICO)
					                VALUES (CONVERT(INTEGER,@vCODIGO_RECETA_MEDICA), @vDESCRIP_USO_MEDICO)
			      FETCH NEXT FROM C_RECM INTO @vCODIGO_RECETA_MEDICA, @vDESCRIP_USO_MEDICO
			   END
			   CLOSE C_RECM
			   DEALLOCATE C_RECM
	        END
		END
	END
