USE FARMACIA_DW
GO

IF EXISTS(SELECT 'X'
            FROM sys.objects
			WHERE type = 'P' AND name = 'EXRACCION_DATOS_DW')
   DROP PROCEDURE EXRACCION_DATOS_DW
GO

DROP PROCEDURE IF EXISTS EXRACCION_DATOS_DW
GO

CREATE PROCEDURE EXRACCION_DATOS_DW(@FechaInicio varchar(10), @FechaFinal varchar(10)) AS
BEGIN
-----------------------------------------------------------------------------------------
-- Tabla: PERSONA
-----------------------------------------------------------------------------------------
   DECLARE
      @vERROR_DATOS       INTEGER,
      @VMENSAJE_ERROR     VARCHAR(4000)

   IF EXISTS (SELECT 'X'
                FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_TYPE='BASE TABLE' 
                 AND TABLE_NAME='DIM_PERSONA')
      IF EXISTS (SELECT 'X'
                   FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES 
                  WHERE TABLE_TYPE='BASE TABLE' 
                    AND TABLE_NAME='PERSONA_SA')
	     BEGIN
		    DECLARE
               @vID_PERSONA            INTEGER,
		       @vNOMBRE_PERSONA		  VARCHAR(50),
			   @vNOMBRE2_PERSONA		  VARCHAR(50),
			   @vAPELLIDO1_PERSONA	  VARCHAR(50),
			   @vAPELLIDO2_PERSONA	  VARCHAR(50),
			   @vCEDULA				  VARCHAR(50)			
			DECLARE C_PERSONA CURSOR FOR
			   SELECT ID_PERSONA,
			          NOMBRE_PERSONA,
					  NOMBRE2_PERSONA,
					  APELLIDO1_PERSONA,
					  APELLIDO2_PERSONA,
					  CEDULA			
			     FROM FARMACIA_SA.dbo.PERSONA_SA SCTA
				WHERE NOT EXISTS (SELECT 'X'
				                    FROM DIM_PERSONA DCTA
								   WHERE DCTA.ID_PERSONA != SCTA.ID_PERSONA)
		    BEGIN
			  SET @VMENSAJE_ERROR = ''
			  SET @vERROR_DATOS   = 0
               OPEN C_PERSONA
			   FETCH NEXT FROM C_PERSONA INTO @vID_PERSONA, @vNOMBRE_PERSONA,@vNOMBRE2_PERSONA,@vAPELLIDO1_PERSONA,@vAPELLIDO2_PERSONA,@vCEDULA
			   WHILE @@FETCH_STATUS = 0
			   BEGIN
			      SET @vERROR_DATOS = 0
			      IF ISNUMERIC(@vID_PERSONA) = 0 OR @vID_PERSONA IS NULL
					 SET @vERROR_DATOS = 1

				  IF @vNOMBRE_PERSONA IS NULL OR LEN(@vNOMBRE_PERSONA) > 50 
				     SET @vERROR_DATOS = 1

				  IF LEN(@vNOMBRE2_PERSONA) > 50 
				     SET @vERROR_DATOS = 1

				  IF @vAPELLIDO1_PERSONA IS NULL OR LEN(@vAPELLIDO1_PERSONA) > 50 
				     SET @vERROR_DATOS = 1

				  IF LEN(@vAPELLIDO2_PERSONA) > 50 
				     SET @vERROR_DATOS = 1

				  IF @vCEDULA IS NULL OR LEN(@vCEDULA) > 50 OR LEN(@vCEDULA) <=13
				     SET @vERROR_DATOS = 1

				  IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN CUENTA: ' + @vID_PERSONA + ' NUM.PER.' + @vNOMBRE_PERSONA + @vNOMBRE2_PERSONA + @vAPELLIDO1_PERSONA + @vAPELLIDO2_PERSONA + @vCEDULA
				  ELSE
			         INSERT INTO DIM_PERSONA(ID_PERSONA, NOMBRE_PERSONA, NOMBRE2_PERSONA,APELLIDO1_PERSONA,APELLIDO2_PERSONA,CEDULA)
					                VALUES (CONVERT(INTEGER,@vID_PERSONA), @vNOMBRE_PERSONA,@vNOMBRE2_PERSONA,@vAPELLIDO1_PERSONA,@vAPELLIDO2_PERSONA,@vCEDULA)
			      FETCH NEXT FROM C_PERSONA INTO @vID_PERSONA, @vNOMBRE_PERSONA,@vNOMBRE2_PERSONA,@vAPELLIDO1_PERSONA,@vAPELLIDO2_PERSONA,@vCEDULA
			   END
			   CLOSE C_PERSONA
			   DEALLOCATE C_PERSONA
	        END
		END
-----------------------------------------------------------------------------------------
-- Tabla: MEDICAMENTO.
-----------------------------------------------------------------------------------------
   IF EXISTS (SELECT 'X'
                FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_TYPE='BASE TABLE' 
                 AND TABLE_NAME='DIM_MEDICAMENTO')
      IF EXISTS (SELECT 'X'
                   FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES 
                  WHERE TABLE_TYPE='BASE TABLE' 
                    AND TABLE_NAME='MEDICAMENTO_SA')
	     BEGIN
		    DECLARE
               @vID_MEDICAMENTO            INTEGER,
		       @vNOMBRE_MEDICAMENTO        VARCHAR(50),
			   @vDESCRIP_MEDICAMENTO       VARCHAR(50)
			DECLARE C_MED CURSOR FOR
			   SELECT ID_MEDICAMENTO,
			          NOMBRE_MEDICAMENTO,
					  DESCRIP_MEDICAMENTO
			     FROM FARMACIA_SA.dbo.MEDICAMENTO_SA SADATA
				WHERE NOT EXISTS (SELECT 'X'
				                    FROM DIM_MEDICAMENTO DWDATA
								   WHERE DWDATA.ID_MEDICAMENTO != SADATA.ID_MEDICAMENTO)
		    BEGIN
			  SET @VMENSAJE_ERROR = ''
			  SET @vERROR_DATOS   = 0
               OPEN C_MED
			   FETCH NEXT FROM C_MED INTO @vID_MEDICAMENTO, @vNOMBRE_MEDICAMENTO
			   WHILE @@FETCH_STATUS = 0
			   BEGIN
			      SET @vERROR_DATOS = 0
			      IF ISNUMERIC(@vID_MEDICAMENTO) = 0 OR @vID_MEDICAMENTO IS NULL
					 SET @vERROR_DATOS = 1

				  IF @vNOMBRE_MEDICAMENTO IS NULL OR LEN(@vNOMBRE_MEDICAMENTO) > 50 or LEN(@vNOMBRE_MEDICAMENTO) <= 2
				     SET @vERROR_DATOS = 1

			      IF @vDESCRIP_MEDICAMENTO IS NULL OR LEN(@vDESCRIP_MEDICAMENTO) > 50 or LEN(@vDESCRIP_MEDICAMENTO) <= 5
				     SET @vERROR_DATOS = 1

				  IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN ESTADO DE CLIENTE: ' + @vID_MEDICAMENTO + ' NOMBRE:' + @vNOMBRE_MEDICAMENTO + ' DESCRIPCIÓN:' + @vDESCRIP_MEDICAMENTO
				  ELSE
			         INSERT INTO DIM_MEDICAMENTO(ID_MEDICAMENTO, NOMBRE_MEDICAMENTO,DESCRIP_MEDICAMENTO)
					                VALUES (CONVERT(INTEGER,@vID_MEDICAMENTO), @vNOMBRE_MEDICAMENTO,@vDESCRIP_MEDICAMENTO)
			      FETCH NEXT FROM C_MED INTO @vID_MEDICAMENTO, @vNOMBRE_MEDICAMENTO, @vDESCRIP_MEDICAMENTO
			   END
			   CLOSE C_MED
			   DEALLOCATE C_MED
	        END
		END
-----------------------------------------------------------------------------------------
-- Tabla: RECETA_MEDICA.
-----------------------------------------------------------------------------------------
IF EXISTS (SELECT 'X'
                FROM INFORMATION_SCHEMA.TABLES 
               WHERE TABLE_TYPE='BASE TABLE' 
                 AND TABLE_NAME='DIM_RECETA_MEDICA')
      IF EXISTS (SELECT 'X'
                   FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES 
                  WHERE TABLE_TYPE='BASE TABLE' 
                    AND TABLE_NAME='RECETA_MEDICA_SA')
	     BEGIN
		    DECLARE
               @vCODIGO_RECETA_MEDICA            INTEGER,
			   @vDESCRIP_USO_MEDICO				 VARCHAR(50)
			DECLARE C_RECM CURSOR FOR
			   SELECT CODIGO_RECETA_MEDICA,
			          DESCRIP_USO_MEDICO
			     FROM FARMACIA_SA.dbo.RECETA_MEDICA_SA SADATA
				WHERE NOT EXISTS (SELECT 'X'
				                    FROM DIM_RECETA_MEDICA DWDATARM
								   WHERE DWDATARM.CODIGO_RECETA_MEDICA != SADATA.CODIGO_RECETA_MEDICA)
		    BEGIN
			  SET @VMENSAJE_ERROR = ''
			  SET @vERROR_DATOS   = 0
               OPEN C_RECM
			   FETCH NEXT FROM C_RECM INTO @vCODIGO_RECETA_MEDICA, @vDESCRIP_USO_MEDICO
			   WHILE @@FETCH_STATUS = 0
			   BEGIN
			      SET @vERROR_DATOS = 0
			      IF ISNUMERIC(@vCODIGO_RECETA_MEDICA) = 0 OR @vCODIGO_RECETA_MEDICA IS NULL
					 SET @vERROR_DATOS = 1

				  IF @vDESCRIP_USO_MEDICO IS NULL OR LEN(@vDESCRIP_USO_MEDICO) > 50 or LEN(@vDESCRIP_USO_MEDICO) <= 2
				     SET @vERROR_DATOS = 1

				  IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN ESTADO DE CLIENTE: ' + @vCODIGO_RECETA_MEDICA + ' DESCRIPCIÓN:' + @vDESCRIP_USO_MEDICO
				  ELSE
			         INSERT INTO DIM_RECETA_MEDICA(CODIGO_RECETA_MEDICA, DESCRIP_USO_MEDICO)
					                VALUES (CONVERT(INTEGER,@vCODIGO_RECETA_MEDICA), @vDESCRIP_USO_MEDICO)
			      FETCH NEXT FROM C_RECM INTO @vCODIGO_RECETA_MEDICA, @vDESCRIP_USO_MEDICO
			   END
			   CLOSE C_RECM
			   DEALLOCATE C_RECM
	        END
		END


	-----------------------------------------------------------------------------------------
	-- Tabla: CATEGORIA MEDICAMENTO
	-----------------------------------------------------------------------------------------
	IF EXISTS (SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'DIM_CATEGORIA_MEDICAMENTO')
	IF EXISTS(SELECT 'X'
		FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'CATEGORIA_MEDICAMENTO_SA')
	BEGIN
		DECLARE
			@vID_TIPO_MED				INTEGER, 
			@vCATEGORIA_MED				VARCHAR(100), 
			@vDESCRIPCION_CATEGORIA_MED	VARCHAR(100)
		DECLARE C_RECM CURSOR FOR
			SELECT 
				ID_TIPO_MED, 
				CATEGORIA_MED,
				DESCRIPCION_CATEGORIA_MED
			FROM FARMACIA_SA.DBO.CATEGORIA_MEDICAMENTO_SA SADATA
			WHERE NOT EXISTS (SELECT 'X'
							FROM DIM_CATEGORIA_MEDICAMENTO DWDATA
							WHERE DWDATA.ID_TIPO_MED != SADATA.ID_TIPO_MED)
			BEGIN
				SET @VMENSAJE_ERROR = ''
				SET @vERROR_DATOS = 0

				OPEN C_RECM
				FETCH NEXT FROM C_RECM INTO @vID_TIPO_MED, @vCATEGORIA_MED, @vDESCRIPCION_CATEGORIA_MED
				WHILE @@FETCH_STATUS = 0
				BEGIN
					SET @vERROR_DATOS = 0
					IF ISNUMERIC(@vID_TIPO_MED) = 0 OR @vID_TIPO_MED IS NULL
						SET @vERROR_DATOS = 1

					IF @vCATEGORIA_MED IS NULL OR LEN(@vCATEGORIA_MED) > 100 or LEN(@vCATEGORIA_MED) <= 2
				     SET @vERROR_DATOS = 1

					IF @vDESCRIPCION_CATEGORIA_MED IS NULL OR LEN(@vDESCRIPCION_CATEGORIA_MED) > 100 or LEN(@vDESCRIPCION_CATEGORIA_MED) <= 2
				     SET @vERROR_DATOS = 1

					IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN CATEGORIA MEDICAMENTO: ' + @vID_TIPO_MED + ' DESCRIPCIÓN:' + @vDESCRIPCION_CATEGORIA_MED

					ELSE 
						INSERT INTO DIM_CATEGORIA_MEDICAMENTO (
							ID_TIPO_MED,
							CATEGORIA_MED,
							DESCRIPCION_CATEGORIA_MED
						) VALUES (
							CONVERT(INTEGER,@vID_TIPO_MED), 
							@vCATEGORIA_MED,
							@vDESCRIPCION_CATEGORIA_MED
						)
					END
				CLOSE C_RECM
				DEALLOCATE C_RECM
			END
		END

	-----------------------------------------------------------------------------------------
	-- Tabla: FARMACIA
	-----------------------------------------------------------------------------------------
	IF EXISTS (SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'DIM_FARMACIA')
	IF EXISTS(SELECT 'X'
		FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'FARMACIA_SA')
	BEGIN
		DECLARE
			@vID_FARMACIA			INTEGER, 
			@vNOMBRE_FARMACIA		VARCHAR(50), 
			@vUBICACION				VARCHAR(50)
		DECLARE C_RECM CURSOR FOR
			SELECT 
				ID_FARMACIA, 
				NOMBRE_FARMACIA,
				UBICACION
			FROM FARMACIA_SA.DBO.FARMACIA_SA SADATA
			WHERE NOT EXISTS (SELECT 'X'
							FROM DIM_FARMACIA DWDATA
							WHERE DWDATA.ID_FARMACIA != SADATA.ID_FARMACIA)
			BEGIN
				SET @VMENSAJE_ERROR = ''
				SET @vERROR_DATOS = 0

				OPEN C_RECM
				FETCH NEXT FROM C_RECM INTO @vID_FARMACIA, @vNOMBRE_FARMACIA, @vUBICACION
				WHILE @@FETCH_STATUS = 0
				BEGIN
					SET @vERROR_DATOS = 0
					IF ISNUMERIC(@vID_FARMACIA) = 0 OR @vID_FARMACIA IS NULL
						SET @vERROR_DATOS = 1

					IF @vNOMBRE_FARMACIA IS NULL OR LEN(@vNOMBRE_FARMACIA) > 50 or LEN(@vNOMBRE_FARMACIA) <= 2
				     SET @vERROR_DATOS = 1

					IF @vUBICACION IS NULL OR LEN(@vUBICACION) > 50 or LEN(@vUBICACION) <= 2
				     SET @vERROR_DATOS = 1

					IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN CATEGORIA FARMACIA: ' + @vID_FARMACIA + ' NOMBRE:' + @vNOMBRE_FARMACIA

					ELSE 
						INSERT INTO DIM_FARMACIA (
							ID_FARMACIA,
							NOMBRE_FARMACIA,
							UBICACION
						) VALUES (
							CONVERT(INTEGER,@vID_FARMACIA), 
							@vNOMBRE_FARMACIA,
							@vUBICACION
						)
					END
				CLOSE C_RECM
				DEALLOCATE C_RECM
			END
		END

	-----------------------------------------------------------------------------------------
	-- Tabla: PRECAUCION
	-----------------------------------------------------------------------------------------
	IF EXISTS (SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'DIM_PRECAUCION')
	IF EXISTS(SELECT 'X'
		FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'PRECAUCION_SA')
	BEGIN
		DECLARE
			@vID_PRECAUCION			INTEGER, 
			@vEFECTOS_SECUNDARIOS	VARCHAR(255), 
			@vFECHA_INDICACION		DATETIME
		DECLARE C_RECM CURSOR FOR
			SELECT 
				ID_PRECAUCION, 
				EFECTOS_SECUNDARIOS,
				FECHA_INDICACIÓN		
			FROM FARMACIA_SA.DBO.PRECAUCION_SA SADATA
			WHERE NOT EXISTS (SELECT 'X'
							FROM DIM_PRECAUCION DWDATA
							WHERE DWDATA.ID_PRECAUCION != SADATA.ID_PRECAUCION)
			BEGIN
				SET @VMENSAJE_ERROR = ''
				SET @vERROR_DATOS = 0

				OPEN C_RECM
				FETCH NEXT FROM C_RECM INTO @vID_PRECAUCION, @vEFECTOS_SECUNDARIOS, @vFECHA_INDICACION
				WHILE @@FETCH_STATUS = 0
				BEGIN
					SET @vERROR_DATOS = 0
					IF ISNUMERIC(@vID_PRECAUCION) = 0 OR @vID_PRECAUCION IS NULL
						SET @vERROR_DATOS = 1

					IF @vEFECTOS_SECUNDARIOS IS NULL OR LEN(@vEFECTOS_SECUNDARIOS) > 50 or LEN(@vEFECTOS_SECUNDARIOS) <= 2
				     SET @vERROR_DATOS = 1

					IF @vFECHA_INDICACION IS NULL
				     SET @vERROR_DATOS = 1

					IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN CATEGORIA PRECAUCION: ' + @vID_PRECAUCION + ' DESCRIPCIÓN:' + @vEFECTOS_SECUNDARIOS

					ELSE 
						INSERT INTO DIM_PRECAUCION (
							ID_PRECAUCION,
							EFECTOS_SECUNDARIOS,
							FECHA_INDICACION
						) VALUES (
							CONVERT(INTEGER,@vID_PRECAUCION), 
							@vEFECTOS_SECUNDARIOS,
							@vFECHA_INDICACION
						)
					END
				CLOSE C_RECM
				DEALLOCATE C_RECM
			END
		END

	-----------------------------------------------------------------------------------------
	-- Tabla: CLIENTE
	-----------------------------------------------------------------------------------------
	IF EXISTS (SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'DIM_CLIENTE')
	IF EXISTS(SELECT 'X'
		FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'CLIENTES_SA')
	BEGIN
		DECLARE
			@vID_CLIENTE			INTEGER, 
			@vFECHA_INICIO		DATETIME
		DECLARE C_RECM CURSOR FOR
			SELECT 
				ID_CLIENTES, 
				FECHA_INICIO	
			FROM FARMACIA_SA.DBO.CLIENTES_SA SADATA
			WHERE NOT EXISTS (SELECT 'X'
							FROM DIM_CLIENTE DWDATA
							WHERE DWDATA.ID_CLIENTE != SADATA.ID_CLIENTES)
			BEGIN
				SET @VMENSAJE_ERROR = ''
				SET @vERROR_DATOS = 0

				OPEN C_RECM
				FETCH NEXT FROM C_RECM INTO @vID_CLIENTE, @vFECHA_INICIO
				WHILE @@FETCH_STATUS = 0
				BEGIN
					SET @vERROR_DATOS = 0
					IF ISNUMERIC(@vID_CLIENTE) = 0 OR @vID_CLIENTE IS NULL
						SET @vERROR_DATOS = 1

					IF @vFECHA_INICIO IS NULL
				     SET @vERROR_DATOS = 1

					IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN CATEGORIA CLIENTE: ' + @vID_CLIENTE 

					ELSE 
						INSERT INTO DIM_CLIENTE (
							ID_CLIENTE,
							FECHA_INICIO
						) VALUES (
							CONVERT(INTEGER,@vID_CLIENTE), 
							@vFECHA_INICIO
						)
					END
				CLOSE C_RECM
				DEALLOCATE C_RECM
			END
		END

	-----------------------------------------------------------------------------------------
	-- Tabla: DISTRIBUIDOR
	-----------------------------------------------------------------------------------------
	IF EXISTS (SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'DIM_DISTRIBUIDOR')
	IF EXISTS(SELECT 'X'
		FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'DISTRIBUIDOR_SA')
	BEGIN
		DECLARE
			@vID_DISTRIBUIDOR				INTEGER, 
			@vFECHA_INICIO_DISTRIBUIDOR		DATETIME
		DECLARE C_RECM CURSOR FOR
			SELECT 
				ID_DISTRIBUIDOR, 
				FECHA_INICIO	
			FROM FARMACIA_SA.DBO.DISTRIBUIDOR_SA SADATA
			WHERE NOT EXISTS (SELECT 'X'
							FROM DIM_DISTRIBUIDOR DWDATA
							WHERE DWDATA.ID_DISTRIBUIDOR != SADATA.ID_DISTRIBUIDOR)
			BEGIN
				SET @VMENSAJE_ERROR = ''
				SET @vERROR_DATOS = 0

				OPEN C_RECM
				FETCH NEXT FROM C_RECM INTO @vID_DISTRIBUIDOR, @vFECHA_INICIO_DISTRIBUIDOR
				WHILE @@FETCH_STATUS = 0
				BEGIN
					SET @vERROR_DATOS = 0
					IF ISNUMERIC(@vID_DISTRIBUIDOR) = 0 OR @vID_DISTRIBUIDOR IS NULL
						SET @vERROR_DATOS = 1

					IF @vFECHA_INICIO_DISTRIBUIDOR IS NULL
				     SET @vERROR_DATOS = 1

					IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN DISTRIBUIDOR: ' + @vID_DISTRIBUIDOR

					ELSE 
						INSERT INTO DIM_DISTRIBUIDOR (
							ID_DISTRIBUIDOR,
							FECHA_INICIO
						) VALUES (
							CONVERT(INTEGER,@vID_DISTRIBUIDOR), 
							@vFECHA_INICIO_DISTRIBUIDOR
						)
					END
				CLOSE C_RECM
				DEALLOCATE C_RECM
			END
		END

	-----------------------------------------------------------------------------------------
	-- Tabla: EMPLEADO
	-----------------------------------------------------------------------------------------
	IF EXISTS (SELECT 'X'
		FROM INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'DIM_EMPLEADO')
	IF EXISTS(SELECT 'X'
		FROM FARMACIA_SA.INFORMATION_SCHEMA.TABLES
		WHERE TABLE_TYPE = 'BASE TABLE'
		AND TABLE_NAME = 'EMPLEADO_SA')
	BEGIN
		DECLARE
			@vIID_EMPLEADO				INTEGER, 
			@vFECHA_INICIO_EMPLEADO		DATETIME
		DECLARE C_RECM CURSOR FOR
			SELECT 
				ID_EMPLEADO, 
				FECHA_INICIO	
			FROM FARMACIA_SA.DBO.EMPLEADO_SA SADATA
			WHERE NOT EXISTS (SELECT 'X'
							FROM DIM_EMPLEADO DWDATA
							WHERE DWDATA.ID_EMPLEADO != SADATA.ID_EMPLEADO)
			BEGIN
				SET @VMENSAJE_ERROR = ''
				SET @vERROR_DATOS = 0

				OPEN C_RECM
				FETCH NEXT FROM C_RECM INTO @vIID_EMPLEADO, @vFECHA_INICIO_EMPLEADO
				WHILE @@FETCH_STATUS = 0
				BEGIN
					SET @vERROR_DATOS = 0
					IF ISNUMERIC(@vIID_EMPLEADO) = 0 OR @vIID_EMPLEADO IS NULL
						SET @vERROR_DATOS = 1

					IF @vFECHA_INICIO_EMPLEADO IS NULL
				     SET @vERROR_DATOS = 1

					IF @vERROR_DATOS = 1
				     SET @VMENSAJE_ERROR = @VMENSAJE_ERROR + ' ERROR EN DISTRIBUIDOR: ' + @vID_DISTRIBUIDOR

					ELSE 
						INSERT INTO DIM_DISTRIBUIDOR (
							ID_DISTRIBUIDOR,
							FECHA_INICIO
						) VALUES (
							CONVERT(INTEGER,@vIID_EMPLEADO), 
							@vFECHA_INICIO_EMPLEADO
						)
					END
				CLOSE C_RECM
				DEALLOCATE C_RECM
			END
		END

	END
